version: '3.8'

services:
  nginx:
    build: ./nginx
    image: custom-nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    depends_on:
      - xslt
      - xquery
    networks:
      - my_network

  xslt:
    build: ./XSLTServer
    image: custom-xslt:latest
    container_name: xslt-server
    volumes:
      - xsltv:/source/data
    networks:
      - my_network

  xquery:
    build: ./xQueryServer
    image: custom-xquery:latest
    container_name: xquery-server
    volumes:
      - xqueryv:/source/data
    networks:
      - my_network

volumes:
  xsltv:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "./public/data/xslt"

  xqueryv:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "./public/data/xquery"

networks:
  my_network:
    driver: bridge
