services:
  nginx:
    build: ./nginx
    image: nginx:xml
    container_name: nginx
    ports:
      - 8000:80
    depends_on:
      - xslt
      - xquery

  xslt:
    build: ./XSLTServer
    image: xslt:xml
    container_name: x-query-server
    volumes:
      -xsltv: /source/data

  xquery:
    build: ./xQueryServer
    image: xquery:xml
    container_name: xslt-server
    volumes:
      -xqueryv: /source/data

volumes:
  xsltv:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "./public/data/xslt"

  xqueryv:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "./public/data/xquery"
