version: '3.8'

services:
  nginx:
    build: ./nginx
    image: custom-nginx:latest
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - xquery
    networks:
      - my_network

  xquery:
    build: ./xQueryServer
    image: custom-xquery:latest
    container_name: xquery-server
    volumes:
      - xqueryv:/source/data
    networks:
      - my_network

volumes:

  xqueryv:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "./public/data/xquery"

networks:
  my_network:
    driver: bridge
