version: '3.8'

services:
  nginx:
    build: ./nginx
    image: custom-nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - xquery
    networks:
      - my_network

  xquery:
    build: ./xQueryServer
    image: custom-xquery:latest
    container_name: xquery-server
    volumes:
      - ./public/data:/source/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
